from .pyroar import PyroarAgent
from .incineroar import IncineroarAgent
from .copperajah import CopperajahAgent
from .hippowdon import HippowdonAgent
from .octillery import OctilleryAgent
from .lycanroc import LycanrocAgent
from .garchomp import GarchompAgent
from .kyogre import KyogreAgent
from .rhyperior import RhyperiorAgent
from .talonflame import TalonflameAgent
from .feraligatr import FeraligatrAgent
from .rapidash import RapidashAgent
from .rillaboom import RillaboomAgent
from .wooloo import WoolooAgent
from .dubwool import DubwoolAgent
from .cinderace import CinderaceAgent
from .stantler import StantlerAgent
from .barraskewda import BarraskewdaAgent
from .ursaring import UrsaringAgent
from .liepard import LiepardAgent
from .kangaskhan import KangaskhanAgent
from .bouffalant import BouffalantAgent
